### ISSUE TITLE
内容抓取

### ISSUE THREAD

**Issue by CS0839** [SpiderClub/weibospider#100]
想问一下大神，您这套工具可不可以实现
1、抓取一个时间段内微博
2、这个时间段内爬取的微博所涉及的所有用户信息（包括粉丝关系、个人属性、抓发评论关系等等）

1、主要是用来分析热词话题
2、主要是用来社区发现，群体发现

自己的水平太次了，跑程序全是报错，也解决不了问题。
所以想问问您这里有这些数据吗，我看有个issue里面有用户的信息和粉丝关系。如果要是有时间戳和微博内容就完美了

**Comment by ResolveWang** [comment]
微博内容抓取可以从两个维度进行，第一个是根据特定关键词进行搜索，第二个根据指定用户抓取他的内容

微博内容和发布时间都可以根据上述两个唯独进行获取，用户信息和分析关系也可以抓取到。

程序报错就详细把你遇到的错误贴出来吧，`1.7.2`发布了很长一段时间了，有一些已知的bug并没有修复，目前修复后的内容在其它几个分支上，还没正式发布。数据的话，我这边几乎没保存，因为我都是需要数据就去抓，抓了就丢了。因此，我还是建议你读完文档后，如果不能解决你的问题，可以把程序的错误和你的操作方式贴出来，这个不用觉得会麻烦我们之类的
