### ISSUE TITLE
user_first与login_first报错1287

### ISSUE THREAD

**Issue by CS0839** [SpiderClub/weibospider#101]
![results](https://user-images.githubusercontent.com/35279052/42161987-a492e0e6-7e2f-11e8-9c8d-f22ee24af4c9.png)
![user_first_warning1287](https://user-images.githubusercontent.com/35279052/42161989-a4df14d4-7e2f-11e8-90f8-562b0bc61861.png)
![login_first_warning1287](https://user-images.githubusercontent.com/35279052/42161991-a5301578-7e2f-11e8-8294-4a55a2951535.png)
报错的原因是截图里results 的原因吗？

**Comment by ResolveWang** [comment]
可能是SQLAlchemy版本有问题，使用sqlalchemy1.15
> pip uninstall sqlalchemy
> pip install sqlalchemy==1.1.15

**Comment by CS0839** [comment]
改了，也没变化

**Comment by CS0839** [comment]
Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  result = self._query(query)
2018-07-02 20:28:16 - crawler - INFO - The login task is starting...

**Comment by ResolveWang** [comment]
这个你google一下吧，我这边已知的用这种方法可以解决。主要是看数据取出来没

**Comment by CS0839** [comment]
好，我再试试

**Comment by CS0839** [comment]
![2018-07-02 21-06-31](https://user-images.githubusercontent.com/35279052/42165842-d1f7989a-7e3b-11e8-9fe2-b38a8f5f7d21.png)
这个pycharm启动login_first 的时候，终端也没有什么提示的

**Comment by ResolveWang** [comment]
因为没从数据库里取出来数据，因此终端并没有任何反应，这个就是问题所在。或者你用`pip install -U sqlalchemy`试试更高版本的`sqlalchemy`，或者试试把你的mysql卸了，重新转mysql 5.6，更多可能的方案可以查看[这里](https://stackoverflow.com/questions/47026599/mysql-giving-deprecated-warning)

**Comment by CS0839** [comment]
谢谢，您能把redis desktop manager 连接到这个工程的配置发我一下吗，这个rdm也是刚下载好，不太会用
![2018-07-02 21-35-44](https://user-images.githubusercontent.com/35279052/42167218-eb3a073a-7e3f-11e8-969d-598b083bd37d.png)

**Comment by CS0839** [comment]
因为跟着您搭建的环境，所以我想配置应该是一样的

**Comment by CS0839** [comment]
![2018-07-02 21-43-40](https://user-images.githubusercontent.com/35279052/42167588-1534b6f6-7e41-11e8-816d-fb89fc238346.png)
您好，这个是已经开始了吧

**Comment by ResolveWang** [comment]
这些问题我觉得你可以自己先查查，看看官网的文档，issue中尽量提搜索引擎搜不到的，且和本项目相关的问题，其它工具的使用建议自己搜索相关东西。
