### ISSUE TITLE
由于昨天mysql的原因，从头开始配了一遍环境，创建一个worker出现了点错误解决不了，

### ISSUE THREAD

**Issue by CS0839** [SpiderClub/weibospider#102]
![2018-07-03 16-17-50](https://user-images.githubusercontent.com/35279052/42207827-6677655a-7e9a-11e8-92ec-351e2b455932.png)

**Comment by CS0839** [comment]
![2018-07-03 16-24-56](https://user-images.githubusercontent.com/35279052/42207995-9942fd64-7e9a-11e8-941f-ad4192423996.png)
这是spider.yaml的配置

**Comment by ResolveWang** [comment]
把配置中的敏感信息去除吧。你这是权限不够，你先在`weibospider`目录创建一个`logs`文件
