### ISSUE TITLE
redis refuse

### ISSUE THREAD

**Issue by CS0839** [SpiderClub/weibospider#103]
![2018-07-03 17-09-53](https://user-images.githubusercontent.com/35279052/42210977-e34c46a2-7ea1-11e8-8082-167ce1a9e865.png)
![2018-07-03 17-10-06](https://user-images.githubusercontent.com/35279052/42210978-e3a06cfa-7ea1-11e8-8f30-30f0764784f9.png)

**Comment by ResolveWang** [comment]
你的redis host配置。。。。
`127.0.0.1`?

额，你就在一个issue里继续问就行了，没必要新开issue

**Comment by CS0839** [comment]
![2018-07-03 20-06-29](https://user-images.githubusercontent.com/35279052/42219248-d297e8ac-7eba-11e8-9b0f-1febc8cc760a.png)
这个里配的没问题啊，在最开始配redis的时候，只设置了bind=0.0.0.0

**Comment by CS0839** [comment]
![2018-07-03 20-17-46](https://user-images.githubusercontent.com/35279052/42219338-1e2a32e8-7ebb-11e8-94a9-b5818ef89d25.png)

**Comment by CS0839** [comment]
![2018-07-03 20-57-13](https://user-images.githubusercontent.com/35279052/42221178-c6f15a78-7ec0-11e8-8f65-400eec84973a.png)
rdm确实通过127.0.0.1可以联通，但是自己的ip连不上，除了spider.yaml，我不记得哪里还会给redis配host

**Comment by ResolveWang** [comment]
你的`spider.yaml`中 `redis:`的host是`172.26xxxx`,但是你`ps aux`查到的`redis监听的是127.0.0.1`，也就是本机地址，因此我的意思是让你把`spider.yaml`中的`host`改成`127.0.0.1`，包括mysql数据库的。我怀疑你的本机地址不是`172.26xxx`，你先改成`127.0.0.1`跑起来吧。

你这知识差的太多了，我都不知道如何帮你

**Comment by CS0839** [comment]
![2018-07-04 07-42-19](https://user-images.githubusercontent.com/35279052/42249449-c86a7d8a-7f1a-11e8-92cc-73652e9da585.png)
![2018-07-04 07-42-31](https://user-images.githubusercontent.com/35279052/42249450-c8b2e9c6-7f1a-11e8-9b8b-2363d0aac50c.png)
配置redis用3.2.9，但是最后requirements里面redis=2.10.5，这个影响不大吗

**Comment by ResolveWang** [comment]
没影响啊，前者是redis server，后者是第三方库。
你先老老实实根据文档操作吧，等程序跑通了再思考别的问题

**Comment by CS0839** [comment]
![2018-07-09 09-42-02](https://user-images.githubusercontent.com/35279052/42426681-613a3592-835c-11e8-8246-5018b9b59339.png)
这个提示表示已经爬去完成了？可是数据量有点少，如何可以继续爬去，让停的时候再停

**Comment by ResolveWang** [comment]
麻烦阅读文档，文档中提了有个定时任务的机制和具体做法。如果是搜索的话，最多只能搜索50页，这个文档也提到过

**Comment by CS0839** [comment]
你这里是说每次（每两个小时）执行搜索任务只能搜索50页，还是说所有总共只能搜索50页。

**Comment by ResolveWang** [comment]
改不了，微博系统限制了，没法改
