### ISSUE TITLE
在win10的环境下celery=3.1.25的版本运行定时任务没有成功

### ISSUE THREAD

**Issue by Ech-ioi** [SpiderClub/weibospider#105]
在《如何构建一个分布式爬虫：理论篇》中的末尾的实践里，我尝试着构建定时任务，并在win10的环境下使用了celery==3.1.25的版本运行，但是等了15分钟左右都没有反应，谷歌了没有找到类似的相同条件下的解决方案，我的代码和教程上的一模一样，求解

**Comment by thekingofcity** [comment]
4.这个项目能在windows上执行吗？

答：window上可以执行worker节点，但是不能执行beat节点（即定时任务）。如果要混用windows和linux，那么一定要将celery版本 降级为3.1.25，且将beat节点部署到linux服务器上。

节点在linux上吗

**Comment by Ech-ioi** [comment]
好的，谢谢，我没有把beat节点部署到linux上。还想多问一下，如果要将beat部署到linux服务器上，worker的启动和beat的启动都需要在Linux上进行吗？还是只需要单独启动beat并在windows上启动worker

**Comment by ResolveWang** [comment]
@Ech-ioi  

如@thekingofcity所说，只需要把beat部署到linux上就行了，worker你部署在windows上也无妨，只不过需要注意两个点
- linux上和windows上的celery版本保持一致，因为可能出现协议上的不兼容
- linux和windows等多个节点应该保持网络互通
