### ISSUE TITLE
mysql 1709 索引长度最大为767,出错

### ISSUE THREAD

**Issue by Grizzy-bear** [SpiderClub/weibospider#110]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
运行 创建超级用户，在存储信息出错

尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？
创建超级用户

3.实际上你得到的结果是什么？

运行到mysql 1709 error 

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by ResolveWang** [comment]
贴一下具体命令和具体错误

**Comment by Grizzy-bear** [comment]
![screenshot at 2018-07-21 20-53-18](https://user-images.githubusercontent.com/29750963/43041236-385c8a28-8d28-11e8-97b9-7501a36ec1a1.png)
上传了

**Comment by ResolveWang** [comment]
weibospider是用的master分支？ master分支不保证能稳定运行，只有`release`中的才保证能根据项目文档稳定运行

**Comment by Grizzy-bear** [comment]
![screenshot at 2018-07-21 20-53-18](https://user-images.githubusercontent.com/29750963/43041400-fd6512dc-8d2c-11e8-929c-94ad116abf79.png)
这个问题是mysql 索引长度的问题，大神是否用的是Innodb引擎？

**Comment by Grizzy-bear** [comment]
![screenshot at 2018-07-21 21-27-52](https://user-images.githubusercontent.com/29750963/43041408-4fb30e22-8d2d-11e8-84c3-cb5836165ffd.png)
这个是MYsql索引长度的问题，大神是否启用了Innodb引擎？

**Comment by ResolveWang** [comment]
高版本的MySQL默认就是InnoDB

**Comment by Grizzy-bear** [comment]
已安装成功， character_set_database设置为utf8就可以了，不过在my.nf里修改的没有用，需要>>ALTER DATABASE databasename CHARACTER SET utf8 COLLATE utf8_general_ci;
另外一个问题，我这个是单机，希望大神能告知单机要设置哪些东西，我对分布式了解的不多，不知从何下手

**Comment by ResolveWang** [comment]
你按照文档操作即可，单机和分布式都一样操作就行了
