### ISSUE TITLE
通过关键字爬取时，无法全文抓取 “展开全文” 部分

### ISSUE THREAD

**Issue by lizhuquan** [SpiderClub/weibospider#111]
版本：2.73
爬取模式已设置为crawling_mode: accurate;
问题：home_crawler  是正常可以展开全文，但search_crawler 任务时， 无法展开全文。 
查看search.py 代码，未发现crawl_ajax_page 执行任务， 只是做了crawl_person_infos 任务。

因此无法确认是代码逻辑问题，还是配置的问题，如有时间，能否提供帮助。 非常感谢！

**Comment by ResolveWang** [comment]
項目release目前最新爲`1.7.2`，沒有你說的tag號...

搜索一下有不有這两段代碼: [page_get/status.py](https://github.com/SpiderClub/weibospider/blob/master/page_get/status.py) , [page_parse/search/get_search_info()](https://github.com/SpiderClub/weibospider/blob/master/page_parse/search.py) 
```
@parse_decorator([])
def get_search_info(html):
    """
    :param html: response content for search with login
    :return: search results
    """
    # 搜索结果可能有两种方式，一种是直接返回的，一种是编码过后的
    content = _search_page_parse(html) if '举报' not in html else html
    if content == '':
        return list()
    soup = BeautifulSoup(content.encode('utf-8', 'ignore').decode('utf-8'), "html.parser")
    feed_list = soup.find_all(attrs={'action-type': 'feed_list_item'})
    search_list = []
    for each in feed_list:
        r = get_weibo_info(each, html)
        if r is not None:
            wb_data = r[0]
            # 看看 你使用的版本中page_parse/search.py中这里是否有下面的处理，没有需要加上才会展开全文
            if r[1] == 0 and CRAWLING_MODE == 'accurate':
                weibo_cont = status.get_cont_of_weibo(wb_data.weibo_id)
                wb_data.weibo_cont = weibo_cont if weibo_cont else wb_data.weibo_cont
            search_list.append(wb_data)
    return search_list
```

因为`1.7.2`这个版本比较久远了，后来进行了一些迭代，所以很多细节忘了。现在事情比较多，所以很多新的功能和特性还没经过足够的测试，以打包到`release`中。

**Comment by ResolveWang** [comment]
既然有那么你就调试一下，在上述代码判断处打印一下是否进入了`if`，然后再在`get_cont_of_weibo()`中打印一下拼凑的URL，打印一下返回的响应， 看看内容是否正确

**Comment by lizhuquan** [comment]
好的。

**Comment by OneCodeMonkey** [comment]
改下接口，参考这个 PR ：
https://github.com/SpiderClub/weibospider/pull/173
