### ISSUE TITLE
Mysql数据库连接问题

### ISSUE THREAD

**Issue by ArchieGu** [SpiderClub/weibospider#113]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
根据项目快速设置里面一步步做下来的。
我的系统是MacOS，Mysql是8.0.12版本
尽量把你的操作过程描述清楚，最好能够复现问题。
我已经按照要求将mysql的编码改为utf-8
![Uploading Screen Shot 2018-08-04 at 9.30.10 PM (2).png…]
然而当我运行create all时仍然报错‘latin-1’
<img width="1280" alt="screen shot 2018-08-04 at 9 31 12 pm" src="https://user-images.githubusercontent.com/19317957/43677009-c112833a-982d-11e8-8baa-89d17443eba0.png">

Mac下安装Python3 时没有找到配置文件去设置ssl，所以那一步暂且跳过了。
2.你期望的结果是什么？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？
使用的是1.7.2版本，常见问题已经阅读了

请问这是怎么一回事呢？

**Comment by ResolveWang** [comment]
mysql客户端执行 `show variables like '%char%';`  截个图看看是否都是`utf8`或者`utf8mb4`

再修改一下`db/basic/get_engine()`函数
```
def get_engine():
    args = get_db_args()
    password = os.getenv('DB_PASS', args['password'])
    # 主要是在连接字符串这里添加  ?charset=utf8mb4
    connect_str = "{}+pymysql://{}:{}@{}:{}/{}?charset=utf8mb4".format(args['db_type'], args['user'], password,
                                                             args['host'], args['port'], args['db_name'])
    engine = create_engine(connect_str, encoding='utf-8')
    return engine
```

**Comment by ArchieGu** [comment]
Hi,

昨天其实已经上传了mysql的截图，结果不小心把链接给弄错了，现在重新上传一张（不好意思哈）
<img width="582" alt="screen shot 2018-08-05 at 10 38 45 am" src="https://user-images.githubusercontent.com/19317957/43682111-c4efbc5c-989b-11e8-8b3e-ad09985e11fa.png">
这是已经修改后的basic_db.py 文件
<img width="1280" alt="screen shot 2018-08-05 at 10 42 40 am" src="https://user-images.githubusercontent.com/19317957/43682136-9d385a10-989c-11e8-9953-6625b164f133.png">


然而运行完毕之后仍然是昨天的错误。伤心ing.
<img width="1280" alt="screen shot 2018-08-05 at 10 43 58 am" src="https://user-images.githubusercontent.com/19317957/43682138-ad1edda0-989c-11e8-8260-7186c405ce40.png">

**Comment by ResolveWang** [comment]
上面没截图那个异常是什么？你的配置文件中是否有特殊字符串？是否可以看看你的配置文件关于数据库的配置？你的Linux服务器是否支持中文？

看截图感觉是对数据库密码加密的时候编码出错了，但是你没给出你的数据库配置相关的信息

**Comment by ArchieGu** [comment]
请问配置文件是指yaml那个文件吗？下面截图是有关数据库的配置：
<img width="370" alt="screen shot 2018-08-05 at 1 49 56 pm" src="https://user-images.githubusercontent.com/19317957/43683044-aa6ebc5a-98b6-11e8-90d3-69f5acf42984.png">

我用的Mac系统，系统语言是英文版……
mysql数据库配置的文件，请问需要您需要看到哪一部分？

**Comment by ResolveWang** [comment]
你改改密码，把特殊字符（`！`）去掉试试

**Comment by ArchieGu** [comment]
Hi,

你说的没有错，去掉！真的能够解决呢。

不过紧接着仍然是数据库连接的问题：

<img width="1280" alt="screen shot 2018-08-05 at 5 50 31 pm" src="https://user-images.githubusercontent.com/19317957/43684751-84db6340-98d8-11e8-95c3-19f290ee9c9c.png">

看了一圈没有找到有关‘tx_isolation’的文件呢。请问你有遇到过这样的情况吗？

**Comment by thekingofcity** [comment]
尝试使用1.1.9版本SQLAlchemy试试
[Issue 80](https://github.com/SpiderClub/weibospider/issues/80)

**Comment by ArchieGu** [comment]
然鹅我用的就是1.1.9版本啊……
