### ISSUE TITLE
InsecureRequestWarning mysql数据库里无数据更新

### ISSUE THREAD

**Issue by ArchieGu** [SpiderClub/weibospider#114]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
按照要求做好了环境配置，能够成功连接数据库、Redis
在数据库中添加了微博账号及登录密码
启动了worker 并且 进行了登录操作（也成功登上了）
紧接着尝试抓取评论 python3 comment_first.py
出现了
[2018-08-05 21:37:30,254: WARNING/ForkPoolWorker-1] /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
这样的情况，mysql数据库中也没有数据更新

我使用的是1.7.2版本
系统为MacOs
![screen shot 2018-08-05 at 9 43 49 pm](https://user-images.githubusercontent.com/19317957/43686455-ae9fcc46-98f8-11e8-8d91-b8c24e645dc0.png)

**Comment by ArchieGu** [comment]
更新一哈：

运行抓取评论数据时，数据库中一直没有数据，爬取主页信息时，数据库里是有数据的

**Comment by ResolveWang** [comment]
评论数据是建立在你已有的微博种子的基础上的，也就是说，你先没抓微博或者没有预插入需要抓取评论的微博id的话，是不会有评论的数据的

**Comment by ArchieGu** [comment]
嗯嗯，谢谢我解决啦~
之前是数据库的可视化程序出问题了导致我误以为没有数据

不好意思。

**Comment by ArchieGu** [comment]
@ResolveWang  

今天尝试重新换一个微博账号爬取 然后遇到了同样的问题。
在使用usr_first.py时能够获取到信息，但使用home_first.py和其他的几个程序时都无法获得数据。

**Comment by ResolveWang** [comment]
没看懂你的问题。

我觉得你没理清楚整个项目的工作流程，有的程序执行会依赖别的任务，因为该任务可能产生相关的种子。还有各个worker执行由于没有优先级，所以可能导致某些类型的worker一直处于待执行状态。短时间内只有某个任务在执行很正常，或者你在多个命令终端中启动多个不同task queue的worker，这样就不会导致任务得不到执行了

建议还是把项目的wiki过一遍吧，你可能对整个项目的工作流程还不了解

**Comment by ArchieGu** [comment]
啊 
我是第一天晚上想要做测试所以开了一个队列。
然后第二天我就把队列所有的信息全部删除了，包括数据库里的seed id那些， redis里面的信息也全部删除了（总之就是想重新爬取不同的微博信息）

比如第一天我再数据库的seed id中添加了A，
第二天我把A的信息从数据库中删除了，也把task都清空，redis都清空（按道理来说再重新开启一个worker并不会受到之前task的影响才对吧？）

然后今天在爬取B的时候，项目一开始什么信息都爬不到，然后就发现A的id又被添加回了seed id。

**Comment by ResolveWang** [comment]
这是因为B的关注或者B的粉丝中有A，所以在抓取B的粉丝和关注的时候，就会将其加入数据库的seed id和relations表中

**Comment by ArchieGu** [comment]
哈哈哈哈，竟然是这样。
不过 我第二天在爬取B的信息的时候（homepage），有很长一段时间数据库都没有更新，大概过了很久之后，数据库中才添加到了B的信息（之前还报了trigger worker什么的错误， 抱歉没有截图记得不是很清楚了）
请问是会出现这样的情况是吗？

**Comment by songyao1994** [comment]
你好，我从GitHub导入最新项目到eclipse，然后上传到centos7配置运行，开启celery许可任务没问题，但是下一步执行python first_task_execution/login_first.py时一直会报这个错误，而且该路径下任何一个py文件都会报这个错误，我试着修改路径来解决这个错误，但是怎么改都还报错，请教这个问题如何解决？

`[root@node6 first_task_execution]# python login_first.py
Traceback (most recent call last):
  File "login_first.py", line 6, in <module>
    from tasks import execute_login_task
  File "../tasks/__init__.py", line 1, in <module>
    from .comment import execute_comment_task
  File "../tasks/comment.py", line 2, in <module>
    from page_parse import comment
  File "../page_parse/comment.py", line 8, in <module>
    from utils import parse_emoji
  File "../utils/parse_emoji.py", line 20, in <module>
    sb_dict = load_emoji_map()
  File "../utils/parse_emoji.py", line 6, in load_emoji_map
    json_data = json.load(open(fn, encoding='utf-8'))
FileNotFoundError: [Errno 2] No such file or directory: 'utils/emoji_ios6.json'`

**Comment by ResolveWang** [comment]
目前releases中的代码数据库部分有一个较小的问题，但是并不影响你的使用，所以尽管放心。这个问题也在[新的分支](https://github.com/SpiderClub/weibospider/tree/dev_wpm)中应该已经修复了，最近较忙，所以一直没更新
