### ISSUE TITLE
关于如何提速的问题

### ISSUE THREAD

**Issue by eefaan** [SpiderClub/weibospider#123]
awesome！首先十分谢谢作者的分享，一个项目坚持迭代一步步完成新想法也是很不容易，更主要是项目稳定性很好，非常实用。

想问的问题是如何在单节点提高爬取速度。

关于爬取速度，wiki中提到修改spider_mode来切换spider的模式，翻了源码发现这样的结果应该只是修改了cookie的使用方式？想提高效率的话还需要继续修改min_crawl_interal和max_crawl_interal这些参数对吗？

但是我将min_crawl_interal设置为1后worker开始大面积飘红，感觉可能是没有请求到页面。更改为2以后能够正常工作但是速度还是不理想。想问问这两个参数的具体含义是什么，如何去改，或者希望作者能给一份高速一点的配置文件参考吗？

本来希望慢慢爬够用就行，但是用default的形式单节点工作了一个多月只抓下来了不到100w，还是有点慢了。

以上

**Comment by ResolveWang** [comment]
`running_mode`确实是修改了cookie的调度方式，它在分布式的环境下，`quick`模式才能发挥最大的效果，这是以牺牲账号为前提的基础上进行的。以前测试过，3台机器3个小时可以抓100万数据。

`min_crawl_interal`和`max_crawl_interal`是一个时间间隔，每次请求的时候都会随机休眠`[min_crawl_interal, max_crawl_interal]`，飘红是啥意思，能贴一下具体错误吗？

目前我有一些简单的想法，也做了一些简单的实验，模拟一个TCP的慢启动，请求间隔还是用的一个默认的间隔，然后在你的网络环境和一个Cookie的队列长度的前提下，让并发线程自增，三个小时没被封，让他的线程变成前一个时间窗口的二倍，直到被封，就减半，然后让线程线性增加，直到被封，这样可以确定出一个登录状态下的一个比较合适的并发请求数，然后用`celery xxxx -c n`进行指定。

我看你的描述，并不清楚你是抓的什么内容，有的内容不需要登录即可抓取，详细可以阅读[这篇文章](https://github.com/SpiderClub/weibospider/wiki/PC%E7%AB%AF%E5%BE%AE%E5%8D%9A%E5%92%8C%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%BE%AE%E5%8D%9A%E7%9A%84%E6%9C%AA%E7%99%BB%E5%BD%95%E6%9D%83%E9%99%90%E6%9D%83%E9%99%90%E5%AF%B9%E6%AF%94%E5%92%8C%E4%BF%A1%E6%81%AF%E5%AE%8C%E6%95%B4%E5%BA%A6%E5%AF%B9%E6%AF%94)，代码可以参考[另外一个分支](https://github.com/SpiderClub/weibospider/tree/dev_wpm)

由于这些东西还没经过长期的测试，所以需要你自己有修改代码的能力可能才能玩得转

**Comment by eefaan** [comment]
其实我之前就想问问我这样改速度没什么大问题吧😂

另外最近做事件检测的小玩具，发现了挺多基于数据流检测的方法，感觉这个spider获取数据的方式有一点缺陷：现在的spider基本是基于用户关系网逐个抓网页，有个问题就是比方说今天抓完了这个大V就标记了已爬，之后他再发新的就不会再抓到了，但是这可能是个意见领袖他的信息权重还挺大，这数据就丢了啊。

换个说法就是这个spider比较像一次性的，挂着一直跑的话数据质量还是有一点缺陷，不过数据质量这东西也是相对数据用途而言的吧。

作者大大考不考虑加个回头的模式，24hours或者48hours回头探索一遍已爬账号的首页有没有新微博。但是简单的回头会增加查重的开销吧，还会浪费挺多时间；如果涉及条件判断的话也不知道分布式好不好做出即时响应。

总之就是一个小想法，还有之前我调的参不会有什么神奇的后果吧😂😂

**Comment by thekingofcity** [comment]
其实简单的回头查重条件判断等不涉及到分布式，毕竟MYSQL是单机的，最多只浪费请求资源

**Comment by eefaan** [comment]
我是觉得请求就是时间，假如想减少时间浪费就要加条件判断提前跳过已经爬过的user，但是在任务队列的模式下等到你判断这个人该跳的时候已经有一批冗余的请求在排队了，也就是不能即时响应吧
