### ISSUE TITLE
mac系统下登录报错ImportError: cannot import name 'parse_decorator'

### ISSUE THREAD

**Issue by songyao1994** [SpiderClub/weibospider#128]
weibospider 最新版本，macos10.13.2
在linux系统的服务器上部署后完美运行，但是下载到自己的电脑后，执行python login_first.py 会报错

![image](https://user-images.githubusercontent.com/35928118/45873030-164a2e00-bdc4-11e8-8f93-1f56d9a449fc.png)

**Comment by thekingofcity** [comment]
检查python版本,启动路径等环境变量
