### ISSUE TITLE
home_first.py获取的微博里面的图片不是高清图，而是缩略图，请问怎么获取高清图片？

### ISSUE THREAD

**Issue by canaanpaul** [SpiderClub/weibospider#129]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
python3 first_task_execution/home_first.py
尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？
数据表weibo_data里面的weibo_img里面的图片都是缩略图图片，我想要高清图片
3.实际上你得到的结果是什么？
数据表weibo_data里面的weibo_img里面的图片都是缩略图图片
4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by thekingofcity** [comment]
貌似把url中的thumb150替换成mw690就是原图网址了
具体的字符串可能需要你仔细测试下了

**Comment by canaanpaul** [comment]
@thekingofcity 多谢！
