### ISSUE TITLE
Cannot get the whole of contents on home page

### ISSUE THREAD

**Issue by fy12105212** [SpiderClub/weibospider#130]
run the spider normally, but cannot get all weibos from the home page, even set the max_home_page=1000. After several experiments, the number of weibos I get is about 40 pages, then the worker will stop automatically.I use release and master codes both, but get the same result. My operation is Ubuntu 16.04 and I have read all documents.

**Comment by thekingofcity** [comment]
What's log at the end of the execution? Could it be either a cookie error or a redis timeout/out of memory?

**Comment by thekingofcity** [comment]
Will be closed if there is no further comment :)
