### ISSUE TITLE
解析comment失败

### ISSUE THREAD

**Issue by weifeng91** [SpiderClub/weibospider#134]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler,comment_crawler,comment_page_crawler,repost_crawler,repost_page_crawler worker -l info -c 1
一台机器是这样，
celery beat -A tasks.workers -l info
另一台机器是这样，
然后执行了登录，user，home，comment命令
尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

3.实际上你得到的结果是什么？
 Failed to parse the page, Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library? is raised, here are details:  File "/home/weifeng/weibospider/decorators/decorators.py", line 47, in handle_error
    return func(*keys)
2018-10-15 10:00:33 - crawler - WARNING - This ip has been blocked by weibo system
[2018-10-15 10:00:33,983: WARNING/ForkPoolWorker-1] This ip has been blocked by weibo system

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by ResolveWang** [comment]
已经提示了
> 2018-10-15 10:00:33 - crawler - WARNING - This ip has been blocked by weibo system

看看你的IP是不是正常
