### ISSUE TITLE
微博展开全文失败，报404

### ISSUE THREAD

**Issue by canaanpaul** [SpiderClub/weibospider#135]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
正常用home_task抓取，发现无法抓到展开全文的内容，发现问题出在
https://s.weibo.com/ajax/direct/morethan140?mid={}
上面的链接不好使了
尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？
希望可以抓到微博长文的内容
3.实际上你得到的结果是什么？
长文的链接返回了404

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by ResolveWang** [comment]
展开全文那个接口微博关闭了，现在只能通过拿到 weibo url，然后访问该url来获取整个微博的内容了

**Comment by OneCodeMonkey** [comment]
改下接口，参考这个 PR ：
#173
