### ISSUE TITLE
微博特定话题搜索任务 没有任何结果

### ISSUE THREAD

**Issue by s29152630** [SpiderClub/weibospider#136]
大大您好, 

我是使用的是目前master code，OS是Red Hat 4.8.5-28，python 3.5.2。
透过admin web设定关键词 "iphone xs"，然后执行了first_task_execution/search_first.py，log并无任何异常，但是却无任何结果新增至mysql中。
于是我去追踪程式码，并将过程印出来，发现确实页面有被爬回来，但是当执行到page_parse/search.py​​ 的_search_page_parse(html) 的时候，我发现m = pattern.search(str(script))的结果总是空的，所以导致get_search_info(html)最后回传的search_list是空的，所以最后就没有结果了。

**Comment by ResolveWang** [comment]
感觉对项目的关注，目前精力有限，未对该项目进行持续的维护，所有有些地方微博页面改版了，项目还没及时更新。
你提的这个问题的原因是微博搜索页面应该发生了改动，我记得好像是大概国庆前后改动的，我这边还未对其进行更新。你如果会Python可以尝试自己修复一下

**Comment by OneCodeMonkey** [comment]
你好，master 分支的 search 任务是可以正常爬取的，具体问题请截图补充下~
