### ISSUE TITLE
 Failed to parse the page, 'NoneType' object has no attribute 'get' is raised

### ISSUE THREAD

**Issue by Heaguang** [SpiderClub/weibospider#137]
大大，您好！
我目前使用的是V1.7.1版本，在执行celery -A tasks.workers -Q login_queue,search_crawler worker -l info -c 1以及python first_task_execution/login_first.py和python first_task_execution/search_first.py后，
总是会出现[ERROR/ForkPoolWorker-1] Failed to parse the page, 'NoneType' object has no attribute 'get' is raised, here are details:  File "/XXX/XXX/weibospider-master/decorators/decorators.py", line 47, in handle_error     return func(*keys)错误，但之后仍然会爬取内容，以前也有这个问题，但是会有爬取内容，虽然现在爬取后数据库没有新的数据，根据您的回答知道了是由于微博页面改版的问题。

**Comment by ResolveWang** [comment]
确实是改版了，异常也比较明显，报的是`parse`模块的问题，下一个月可能我会继续更新这个项目。

精力确实也不是很够，见谅

**Comment by OneCodeMonkey** [comment]
最新版的爬虫页面解析，search 搜索页实测是可用的。您这边不妨再试试。不过要注意账号受限制的话是请求不到搜索页的结果的。如果还有问题可以重提 issue。感谢关注本项目~
