### ISSUE TITLE
评论的创建时间格式如何调整

### ISSUE THREAD

**Issue by songyao1994** [SpiderClub/weibospider#139]
使用的是1.7.2版本，一切正常，但是爬取的评论的创建时间不是格式化的，而是1分钟前、今天11:20，请问应该修改哪一个文件？

**Comment by ResolveWang** [comment]
这是由于微博改版了，目前暂未更新

**Comment by songyao1994** [comment]
写了一个小util，规整时间格式

`import pymysql
import re
import time


def getFormat():

    # 打开数据库连接
    db = pymysql.connect(
        host='192.168.1.85',
        port=3306,
        user='root',
        passwd='root',
        db='weibo',
        charset='utf8'
    )
    # 使用cursor()方法获取操作游标
    cursor = db.cursor()

    for id in range(13894, 13895):
        # SQL  语句
        sql = "SELECT * FROM weibo_comment where id = '%s'  "% (id)
        # sql = "SELECT * FROM weibo_comment where id = '15025' "
        # sql = "SELECT * FROM weibo_comment where id = '456' "

        cursor.execute(sql)

        cursor.rowcount
        # 返回被execute影响的数据的行数,注：execute不是方法.
        get_row = cursor.fetchone()
        create_datetime =re.split(r' ', get_row[5])
        create_dates = create_datetime[0]
        create_time = create_datetime[1]
        regex_str = ".*?([\u4E00-\u9FA5]+)"
        match_obj = re.match(regex_str, get_row[5])
        if match_obj:
            regex_result = match_obj.group(1)

        if regex_result == "今天" :
            create_month=time.strftime('%m',time.localtime(time.time()))
            create_day=time.strftime('%d',time.localtime(time.time()))
        elif regex_result == "分钟前"  or regex_result == "秒前":
            create_month = time.strftime('%m', time.localtime(time.time()))
            create_day = time.strftime('%d', time.localtime(time.time()))
            create_time = time.strftime('%H:%M', time.localtime(time.time()))
        else  :
            create_date = re.split(r'日|月',create_dates)
            if len(create_date[1])==1 :
                create_month =  create_date[0]
                create_day = "0"+create_date[1]
            else:
                if len(create_date[0])==1 :
                    create_month = "0"+create_date[0]
                    create_day =  create_date[1]
                else:
                    create_month = create_date[0]
                    create_day = create_date[1]

        # 取结果集下一行
        result = "2018-"+create_month+"-"+create_day+" "+create_time

        print(result)

        # 修改表(test)表中ID 为1 的value 为 10
        sql_update = "update weibo_comment set create_time = '%s' where id = '%s' " % (result,id)
        cursor.execute(sql_update)

        # 非常重要，在这里卡了很久 pymysql在连接数据库的时候会有一个参数autocommit默认为False，表示执行完SQL语句后是否自动提交到真正的数据库，如果没有设置为True，那么你执行sql过后，是需要显式提交的，即conn.commit()
        db.commit()
        print(get_row)


    # 关闭游标
    cursor.close()
    # 关闭数据库连接
    db.close()


def main( ):
    getFormat()


main()`

**Comment by songyao1994** [comment]
写了一个修改时间格式的
`import pymysql
import re
import time


def getFormat():

    # 打开数据库连接
    db = pymysql.connect(
        host='192.168.1.85',
        port=3306,
        user='root',
        passwd='root',
        db='weibo',
        charset='utf8'
    )
    # 使用cursor()方法获取操作游标
    cursor = db.cursor()

    for id in range(13894, 13895):
        sql = "SELECT * FROM weibo_comment where id = '%s'  "% (id)
        cursor.execute(sql)
        cursor.rowcount
        get_row = cursor.fetchone()
        create_datetime =re.split(r' ', get_row[5])
        create_dates = create_datetime[0]
        create_time = create_datetime[1]
        regex_str = ".*?([\u4E00-\u9FA5]+)"
        match_obj = re.match(regex_str, get_row[5])
        if match_obj:
            regex_result = match_obj.group(1)

        if regex_result == "今天" :
            create_month=time.strftime('%m',time.localtime(time.time()))
            create_day=time.strftime('%d',time.localtime(time.time()))
        elif regex_result == "分钟前"  or regex_result == "秒前":
            create_month = time.strftime('%m', time.localtime(time.time()))
            create_day = time.strftime('%d', time.localtime(time.time()))
            create_time = time.strftime('%H:%M', time.localtime(time.time()))
        else  :
            create_date = re.split(r'日|月',create_dates)
            if len(create_date[1])==1 :
                create_month =  create_date[0]
                create_day = "0"+create_date[1]
            else:
                if len(create_date[0])==1 :
                    create_month = "0"+create_date[0]
                    create_day =  create_date[1]
                else:
                    create_month = create_date[0]
                    create_day = create_date[1]

        result = "2018-"+create_month+"-"+create_day+" "+create_time

        print(result)

        sql_update = "update weibo_comment set create_time = '%s' where id = '%s' " % (result,id)
        cursor.execute(sql_update)

        # pymysql在连接数据库的时候会有一个参数autocommit默认为False，表示执行完SQL语句后是否自动提交到真正的数据库，如果没有设置为True，那么你执行sql过后，是需要显式提交的，即conn.commit()
        db.commit()
        print(get_row)

    cursor.close()
    db.close()

def main( ):
    getFormat()


main()`

**Comment by thekingofcity** [comment]
方便的话可以PR提交一下哦
