### ISSUE TITLE
这个界面为啥一直持续着。。The login task is starting...

### ISSUE THREAD

**Issue by FDU-SDS** [SpiderClub/weibospider#141]
(python35) ➜  weibospider git:(master) ✗ python first_task_execution/login_first.py
2018-11-10 20:23:20 - crawler - INFO - The login task is starting...

步骤是严格按照主页来的

**Comment by FDU-SDS** [comment]
已解决～

**Comment by CUHKSZCHEN** [comment]
求问如何解决的谢谢！
