### ISSUE TITLE
大佬可以发布下稳定的1.7.3版本吗。。。。

### ISSUE THREAD

**Issue by FDU-SDS** [SpiderClub/weibospider#143]
感觉1.7.3版本爬的内容更全。。。

**Comment by ResolveWang** [comment]
下一个版本可能在元旦吧，目前还有更重要的事情要做

**Comment by BatheFu** [comment]
感谢大佬，目前1.7.3在执行login_first的时候会报错：ImportError: cannot import name 'get_session'

如果年后能进行关键词搜索就太感谢啦～

**Comment by OneCodeMonkey** [comment]
> 感谢大佬，目前1.7.3在执行login_first的时候会报错：ImportError: cannot import name 'get_session'
> 
> 如果年后能进行关键词搜索就太感谢啦～

关键词搜索？是根据话题名去采集么？这个可以做的，tasks/search.py 里面指定关键词：#关键词#

**Comment by OneCodeMonkey** [comment]
话题名可以采集，另外有种方式可以实现几乎全量话题的内容采集（默认采集的是“原创分类”）。就是按微博的筛选条件，每隔一小时间隔去采集一次 50 页的全量。这种方式我自己采全量用的效果非常好。
