### ISSUE TITLE
redis 内存溢出，db5数据量太大，超过20G，

### ISSUE THREAD

**Issue by Muzixin** [SpiderClub/weibospider#148]
爬虫正常运行一个多月，突然出现redis.exceptions.ResponseError: OOM command not allowed when used memory > 'maxmemory'.错误? 在删除DB5里面的comment和home的数据之后，正常运行，分析原因是因为该字段的数据太大，请问有什么解决办法吗？

**Comment by ResolveWang** [comment]
任务堆积太多，翻一下celery的文档，我记得应该是有任务过期的设置的

**Comment by Muzixin** [comment]
> 任务堆积太多，翻一下celery的文档，我记得应该是有任务过期的设置的

先测试一下，是不是这个问题
