### ISSUE TITLE
环境配置Ubuntu16.04 安装Python3.5.2中的openssl-devel包

### ISSUE THREAD

**Issue by februarysea** [SpiderClub/weibospider#149]
安装Python3.5.2中的openssl-devel包
使用 `yum install openssl-devel -y` 命令
报错如下：

> There are no enabled repos.
>  Run "yum repolist all" to see the repos you have.
>  You can enable repos with yum-config-manager --enable <repo>

使用下面两行命令，安装成功
`sudo apt-get install openssl` 
`sudo apt-get install libssl-dev`

**Comment by sev7e0** [comment]
Ubuntu还是推荐使用apt-get,centos这类使用yum比较多
