### ISSUE TITLE
page not found 404  

### ISSUE THREAD

**Issue by wczqhd** [SpiderClub/weibospider#150]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
python3 admin/manage.py makemigrations
python3 admin/manage.py migrate
python3 admin/manage.py createsuperuser
python3 admin/manage.py runserver 0.0.0.0:8000
尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？
期望能够运行django
3.实际上你得到的结果是什么？
![_20181225021929](https://user-images.githubusercontent.com/5190069/50405155-93ce7180-07eb-11e9-88d4-9813e16bd2f5.png)

page not found 404
4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？
读过常见问题；系统ubuntu16.04; 用的最新版weibospider; python3.6.4; django 2.1.4; mysql 14.14
我自己用django做了个helloworld可以正常runserver。

**Comment by ResolveWang** [comment]
精力有限，web页面目前不维护了

**Comment by OneCodeMonkey** [comment]
> 在提交Issue之前请先回答下面问题，谢谢！
> 
> 1.你是怎么操作的？
> python3 admin/manage.py makemigrations
> python3 admin/manage.py migrate
> python3 admin/manage.py createsuperuser
> python3 admin/manage.py runserver 0.0.0.0:8000
> 尽量把你的操作过程描述清楚，最好能够复现问题。
> 
> 2.你期望的结果是什么？
> 期望能够运行django
> 3.实际上你得到的结果是什么？
> ![_20181225021929](https://user-images.githubusercontent.com/5190069/50405155-93ce7180-07eb-11e9-88d4-9813e16bd2f5.png)
> 
> page not found 404
> 4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？
> 读过常见问题；系统ubuntu16.04; 用的最新版weibospider; python3.6.4; django 2.1.4; mysql 14.14
> 我自己用django做了个helloworld可以正常runserver。

你好。django 版本换成 1.11.x 试下，
