### ISSUE TITLE
expected string or bytes-like object is raised

### ISSUE THREAD

**Issue by abelard2008** [SpiderClub/weibospider#157]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
打开两个终端:
第一个终端的主目录下执行:
celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler,repost_crawler,repost_page_crawler,praise_crawler,praise_page_crawler worker -l info -c 1

第二个终端执行:
python3 first_task_execution/home_first.py

对某些帐号,得到
ERROR/ForkPoolWorker-1] Failed to parse the page, expected string or bytes-like object is raised, here are details:  File "/develop/remote-info/caipan/weibospider/decorators/decorators.py", line 47, in handle_error

跟踪了一下, 原因是:
https://github.com/SpiderClub/weibospider/blob/master/page_parse/home.py#L36 
的:
m = pattern.search(script.string)
当遇到:
script.string = <script src=""></script> (比如我遇到的: 
<script src="//js.t.sinajs.cn/t6/home/js/pl/top/topInit.js?version=edef3632d17f5fb3"></script>
)
则 script.string 为 None 所致
尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？
不出错误, ^_^

3.实际上你得到的结果是什么？
异常
4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题]
最新版, Fedora 29 X86_64
(https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by thekingofcity** [comment]
See [PR158](https://github.com/SpiderClub/weibospider/pull/158)
