### ISSUE TITLE
DB operation error

### ISSUE THREAD

**Issue by xiaozhuo1314** [SpiderClub/weibospider#160]
按照README上的操作方法一步步执行后，可以启动登录以及进行搜索，但是爬取comment信息时会出现如下错误，搜索了百度说是没有将上一个session rollback，但是小白不知道应该在哪和怎么加，所以特来开issue询问，谢谢！
在运行过程中因为html5lib库没有安装就崩溃了，再次执行就出现了这个错误。
WeiboSpider为最新版的master分支，运行在Ubuntu18.04上。
具体错误信息如下：

`[2019-04-16 09:22:35,492: ERROR/ForkPoolWorker-1] DB operation error，here are details:This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1062, "Duplicate entry '4361454835035582' for key 'comment_id'") [SQL: 'INSERT INTO weibo_comment (comment_id, comment_cont, comment_screen_name, weibo_id, user_id, create_time) VALUES (%(comment_id)s, %(comment_cont)s, %(comment_screen_name)s, %(weibo_id)s, %(user_id)s, %(create_time)s)'] [parameters: {'comment_id': '4361454835035582', 'comment_cont': '【瑞达法考 2019法律职业资格考试瑞达e学考点e本通班网络课程 预售... ', 'comment_screen_name': '瑞达刑诉法张晶', 'weibo_id': '4361418750382877', 'user_id': '6569577946', 'create_time': '20194月15日 21:35 '}]`

**Comment by ResolveWang** [comment]
这条数据已经有了
>  "Duplicate entry '4361454835035582'

这个错误严格说并不算业务上的错误，它只是提示数据已经存在而已

**Comment by xiaozhuo1314** [comment]
确实已经有了。谢谢解答！
