### ISSUE TITLE
Newer version 4.3.0 of celery might stop the worker

### ISSUE THREAD

**Issue by thekingofcity** [SpiderClub/weibospider#162]
newer version of celery==4.3.0 which comes with kombu==4.5.0 will stop the worker.

celery|kombu|result
-|-|-
4.2.1|4.2.1|✔
4.2.1|4.5.0|❌
4.3.0|4.5.0|❌

Since requirements.txt does not specifiy kombu version, the celery will install kombu==4.5.0 which will stop the worker.

**Comment by thekingofcity** [comment]
```
root@crawler9:~/weibospider# celery -A tasks.workers -Q user_crawler,user_name_crawler worker -l info -c 3
/usr/local/lib/python3.6/dist-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
 
 -------------- celery@crawler9 v4.3.0 (rhubarb)
---- **** ----- 
--- * ***  * -- Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic 2019-04-21 14:35:31
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         weibo_task:0x7f8462048e48
- ** ---------- .> transport:   redis://:**@10.1.96.4:57392/5
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 3 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> user_crawler     exchange=user_crawler(direct) key=for_user_info

[tasks]
  . tasks.comment.crawl_comment_by_page
  . tasks.comment.crawl_comment_page
  . tasks.dialogue.crawl_dialogue
  . tasks.dialogue.crawl_dialogue_by_comment_id
  . tasks.dialogue.crawl_dialogue_by_comment_page
  . tasks.downloader.download_img_task
  . tasks.home.crawl_ajax_page
  . tasks.home.crawl_weibo_datas
  . tasks.login.login_task
  . tasks.praise.crawl_praise_by_page
  . tasks.praise.crawl_praise_page
  . tasks.repost.crawl_repost_by_page
  . tasks.repost.crawl_repost_page
  . tasks.search.execute_search_task
  . tasks.search.search_keyword
  . tasks.user.crawl_follower_fans
  . tasks.user.crawl_person_infos

root@crawler9:~/weibospider# 
```

**Comment by youareswj** [comment]
我也遇到这个问题
![1556443967(1)](https://user-images.githubusercontent.com/25320424/56862263-bfe94180-69db-11e9-8d65-5d1dae3a9fa3.jpg)
但 requirements.txt 里面是这个版本的，请问是因为版本原因不能运行worker吗？
![1556444110(1)](https://user-images.githubusercontent.com/25320424/56862295-0ccd1800-69dc-11e9-97d8-b6fe6a6c2115.jpg)

**Comment by thekingofcity** [comment]
> 我也遇到这个问题
> ![1556443967(1)](https://user-images.githubusercontent.com/25320424/56862263-bfe94180-69db-11e9-8d65-5d1dae3a9fa3.jpg)
> 但 requirements.txt 里面是这个版本的，请问是因为版本原因不能运行worker吗？
> ![1556444110(1)](https://user-images.githubusercontent.com/25320424/56862295-0ccd1800-69dc-11e9-97d8-b6fe6a6c2115.jpg)

见[Issue 112](https://github.com/SpiderClub/weibospider/issues/112)

**Comment by youareswj** [comment]
ok thk

**Comment by youareswj** [comment]
> > 我也遇到这个问题
> > 但requirements.txt里面是这个版本的，请问是因为版本原因不能运行worker吗？
> > ![1556443967(1)](https://user-images.githubusercontent.com/25320424/56862263-bfe94180-69db-11e9-8d65-5d1dae3a9fa3.jpg)
> > ![1556444110(1)](https://user-images.githubusercontent.com/25320424/56862295-0ccd1800-69dc-11e9-97d8-b6fe6a6c2115.jpg)
> 
> 见[Issue 112](https://github.com/SpiderClub/weibospider/issues/112)

ok thk!

**Comment by OneCodeMonkey** [comment]
celery==4.3.0
kombu==4.6.4
这个版本组合可以完美运行，试下~

**Comment by thekingofcity** [comment]
> 
> 
> celery==4.3.0
> kombu==4.6.4
> 这个版本组合可以完美运行，试下~

这个我也试了不行啊, 顺带一提最新的
celery==4.4.0
kombu==4.6.7
好像也不行, 惊了
