### ISSUE TITLE
报错requests.exceptions.ConnectionError: HTTPSConnectionPool(host='passport.weibo.com', port=443): Max retries exceeded with url: /visitor/genvisitor

### ISSUE THREAD

**Issue by buzhaodiao** [SpiderClub/weibospider#163]
请教大佬，用的最新的master版本的weibospider，系统是ubuntu18.04，在执行  celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler worker -l info -c 1  的时候报错如图，网上搜到有个类似的问题，不知道是不是一样，不太清楚headers里面key值都加上是什么意思。

![TIM截图20190426124046](https://user-images.githubusercontent.com/35843297/56784048-4d346680-6821-11e9-983f-52cbcb14a9f7.png)

![TIM截图20190426124122](https://user-images.githubusercontent.com/35843297/56784057-545b7480-6821-11e9-8c15-9a93e75b8edb.png)

**Comment by ResolveWang** [comment]
你看看你手动能用那个账号和IP访问不，那句话的意思是你把HTTP Request包中的Headers参数都复制到项目的Headers中

**Comment by buzhaodiao** [comment]
> 你看看你手动能用那个账号和IP访问不，那句话的意思是你把HTTP Request包中的Headers参数都复制到项目的Headers中

这个问题没了，是我虚拟机网络问题。。。
