### ISSUE TITLE
用户主页的新内容不能抓取

### ISSUE THREAD

**Issue by zengjian** [SpiderClub/weibospider#164]
**1.你是怎么操作的？**

我设置了10分钟抓取一次用户主页，并用自己的微博账号进行测试，不断的发新的内容
在窗口A执行了如下命令，抓评论:
`celery -A tasks.workers -Q login_queue,comment_crawler worker -l info -c 1`

在窗口B执行了如下命令，抓用户主页等：
`celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler worker -l info -c 1`

在窗口C执行了如下命令：
`celery beat -A tasks.workers -l info`

**2.你期望的结果是什么？**

我期望每隔10分钟就能把新的主页内容抓到了weibo_data表中。

**3.实际上你得到的结果是什么？**

实际上没有新的数据加入，但评论抓取是正常的。
如果我修改用户“是否已采集主页”为0，则可以抓取到新的主页内容。难道用户的主页被设置成只抓取一次么，那有新的内容要抓取该如何设置？

**4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？**

checkout的master分支，操作系统macos 10.14

**Comment by ResolveWang** [comment]
可能是新数据增量抓取那里的判断有点问题，你需要自己修改一下[home.py](https://github.com/SpiderClub/weibospider/blob/master/tasks/home.py)中的`crawl_weibo_datas`函数，它包含了增量抓取的逻辑

**Comment by zengjian** [comment]
找到问题了，原来
在dao.py中有如下代码：

```
    def get_home_ids(cls):
        """
        Get all user id who's home pages need to be crawled
        :return: user ids
        """
        #return db_session.query(SeedIds.uid).filter(text('home_crawled=0')).all()
        return db_session.query(SeedIds.uid).all()
```

上面注掉的代码是原代码，他只会取未抓取过的主页，改成下面的就会每次遍历账号抓取主页了。
