### ISSUE TITLE
Message Error: Couldn't apply scheduled task user_task: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.

### ISSUE THREAD

**Issue by buzhaodiao** [SpiderClub/weibospider#165]
用的最新的master版本的weibospider，系统是ubuntu18.04，运行`celery beat -A tasks.workers -l info`一段时间后出现这种错误，同时运行`celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler,comment_crawler,comment_page_crawler,repost_crawler,repost_page_crawler,praise_crawler,praise_page_crawler worker -l info -c 1`的cmd也自动退出（最后一图）

![TIM截图20190426195805](https://user-images.githubusercontent.com/35843297/56806136-a5895980-685d-11e9-8aa2-5cf264c76f2a.png)

![TIM截图20190426194712](https://user-images.githubusercontent.com/35843297/56806144-ad48fe00-685d-11e9-9ccf-f8fa0c2ebddb.png)

![TIM截图20190426195025](https://user-images.githubusercontent.com/35843297/56806155-b33edf00-685d-11e9-81c8-0da283136b82.png)

**Comment by ResolveWang** [comment]
你这明显是Redis配置有问题啊，Redis日志用AOF吧，怎么设置自己搜一下，另外注意启动redis时候指定配置文件

**Comment by buzhaodiao** [comment]
> 你这明显是Redis配置有问题啊，Redis日志用AOF吧，怎么设置自己搜一下，另外注意启动redis时候指定配置文件

ok，我试试
