### ISSUE TITLE
No cookie in cookies pool. Maybe all accounts are banned, or all cookies are expired

### ISSUE THREAD

**Issue by buzhaodiao** [SpiderClub/weibospider#166]
执行`celery -A tasks.workers -Q login_queue,user_crawler,fans_followers,search_crawler,home_crawler worker -l info -c 1`之后出现这个错误，我数据库里有两个微博账号，都启用了，网页微博登陆账号进行一些操作时提示以下信息，感觉是被禁了，配置文件我使用的默认配置，请问调整哪些配置能够预防这种情况呢？

![TIM截图20190506162531](https://user-images.githubusercontent.com/35843297/57215113-8ee1c000-701e-11e9-8022-2792b981d3f9.png)

![TIM截图20190506163748](https://user-images.githubusercontent.com/35843297/57215116-8f7a5680-701e-11e9-9539-273777014a83.png)

**Comment by ResolveWang** [comment]
这是账号被禁了啊，只能设置更大的抓取时间间隔，如果要稳定抓取的话

**Comment by buzhaodiao** [comment]
> 这是账号被禁了啊，只能设置更大的抓取时间间隔，如果要稳定抓取的话

我修改这两项就可以了吧

![TIM截图20190507162317](https://user-images.githubusercontent.com/35843297/57284915-b26f3e00-70e4-11e9-8bb2-16719b1696a7.png)
