### ISSUE TITLE
全部按正常流程进行的，最后启动worker命令失败，输出日志如下

### ISSUE THREAD

**Issue by OneCodeMonkey** [SpiderClub/weibospider#170]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？

尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

-------------- celery@vagrant v4.1.0 (latentcall)                                                   
---- **** -----                                                                                     
 --- * ***  * -- Linux-4.4.0-157-generic-x86_64-with-Ubuntu-16.04-xenial 2019-08-16 02:58:14          
-- * - **** ---                                                                                      
- ** ---------- [config]                                                                             
- ** ---------- .> app:         weibo_task:0x7feb46975438                                            
- ** ---------- .> transport:   redis://:**@127.0.0.1:6379/5                                         
- ** ---------- .> results:     disabled://                                                          
- *** --- * --- .> concurrency: 1 (prefork)                                                          
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)                     
 --- ***** -----                                                                                       
-------------- [queues]                                                                                             .> ajax_home_crawler exchange=ajax_home_crawler(direct) key=ajax_home_info                           .> comment_crawler  exchange=comment_crawler(direct) key=comment_info                                .> comment_page_crawler exchange=comment_page_crawler(direct) key=comment_page_info                  .> fans_followers   exchange=fans_followers(direct) key=for_fans_followers                           .> home_crawler     exchange=home_crawler(direct) key=home_info                                      .> login_queue      exchange=login_queue(direct) key=for_login                                       .> repost_crawler   exchange=repost_crawler(direct) key=repost_info                                  .> repost_page_crawler exchange=repost_page_crawler(direct) key=repost_page_info                     .> search_crawler   exchange=search_crawler(direct) key=for_search_info                              .> user_crawler     exchange=user_crawler(direct) key=for_user_info                                                                                                                       [tasks]                                                                                                . tasks.comment.crawl_comment_by_page                                                                . tasks.comment.crawl_comment_page                                                                   . tasks.comment.excute_comment_task                                                                  . tasks.home.crawl_ajax_page                                                                         . tasks.home.crawl_weibo_datas                                                                       . tasks.home.excute_home_task                                                                        . tasks.login.excute_login_task                                                                      . 
tasks.login.login_task                                                                             . tasks.repost.crawl_repost_by_page                                                                  . tasks.repost.crawl_repost_page                                                                     . tasks.repost.excute_repost_task                                                                    . tasks.search.excute_search_task                                                                    . tasks.search.search_keyword                                                                        . tasks.user.crawl_follower_fans                                                                     . tasks.user.crawl_person_infos                                                                      . 
tasks.user.excute_user_task                                                                                                                     
[2019-08-16 02:58:14,834: INFO/MainProcess] Connected to redis://:**@127.0.0.1:6379/5   
[2019-08-16 02:58:14,860: INFO/MainProcess] mingle: searching for neighbors                          
[2019-08-16 02:58:15,903: INFO/MainProcess] mingle: all alone                                        
vagrant@vagrant:/home/www/weibospider$
--
求助各位又没碰到过类似的问题?...

**Comment by bgmnbear** [comment]
Hi.

Please write the issue in the format provided, thanks.

And did you follow the [setting](https://github.com/SpiderClub/weibospider/wiki/%E5%88%86%E5%B8%83%E5%BC%8F%E7%88%AC%E8%99%AB%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE) to build your project?

Best,
Whister.

**Comment by OneCodeMonkey** [comment]
已解决。能启动。执行下 `pip3 install -U celery` 升级到 4.3 版本，kombu 按报错提示升级到 4.6.4 ，切换到源代码的 master，启动成功爬到数据了。
