### ISSUE TITLE
worker启动后会自动的退出

### ISSUE THREAD

**Issue by holoodst** [SpiderClub/weibospider#176]
您好 我使用的是最新的版本，我希望完成的任务是抓取微博特定话题的转发点赞以及评论数目，我目前遇见的情况是输入celery -A tasks.workers worker -l info -c 1后worker自动退出，导致没有办法发命令 

![image](https://user-images.githubusercontent.com/25474798/71160420-7a3afb00-2282-11ea-89b1-d4b9920e3f25.png)

**Comment by OneCodeMonkey** [comment]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的常见问题？

**Comment by OneCodeMonkey** [comment]
看下 redis 是否能正常连接，redis 是否设置有密码。这些前置操作都会影响 worker 导致异常退出。
