### ISSUE TITLE
根据说明文档执行，这个程序运行不了

### ISSUE THREAD

**Issue by GXNU156489** [SpiderClub/weibospider#179]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
按照readme执行后，没有结果
![TIM图片20200107191903](https://user-images.githubusercontent.com/36919834/71891920-a27f9080-3182-11ea-9ac3-54c21a1adf8f.png)
![TIM图片20200107191910](https://user-images.githubusercontent.com/36919834/71891921-a3182700-3182-11ea-8eba-30b34b545b85.png)
![TIM图片20200107191915](https://user-images.githubusercontent.com/36919834/71891922-a3182700-3182-11ea-8960-35dc1acf6fdd.png)

尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by thekingofcity** [comment]
第一张图没有完整执行路径无法判断错误原因, 猜测和venv配置有关
剩余两张图看起来没有任何问题, 这是正常执行的状态

PS 不要忘记windows不是支持的客户端

**Comment by OneCodeMonkey** [comment]
1. 启动 celery worker 后的完整打印结果，截图发一下
2.数据库表里有一张 login_info，里面是否有可用的微博账号？

**Comment by OneCodeMonkey** [comment]
windows 直接跑这个有点诡异吧。。。建议 windows 上用 vagrant 起一个linux 的虚拟机来跑， @GXNU156489

**Comment by GXNU156489** [comment]
好的，谢谢您的回复，我这几天在外地，我回到工作地后，马上给您回信，再次感谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "刘洋 Jax"<notifications@github.com&gt;; 
发送时间: 2020年1月8日(星期三) 晚上10:22
收件人: "SpiderClub/weibospider"<weibospider@noreply.github.com&gt;; 
抄送: "龙潜贰柒"<980906165@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SpiderClub/weibospider] 根据说明文档执行，这个程序运行不了 (#179)



 
启动 celery worker 后的完整打印结果，截图发一下
 2.数据库表里有一张 login_info，里面是否有可用的微博账号？
