### ISSUE TITLE
云打码是不是凉了

### ISSUE THREAD

**Issue by xwt0016** [SpiderClub/weibospider#181]
www.yundama.com 云打码官网似乎打不开了

**Comment by thekingofcity** [comment]
可以提供更多信息吗?

**Comment by OneCodeMonkey** [comment]
好像是额，刚发现云打码官网打不开，API 也不通了。。 @thekingofcity @xwt0016 @ResolveWang

**Comment by OneCodeMonkey** [comment]
刚发现的，不知道是从什么时候开始的。保佑别跑路了，里面还好多余额呢。。

**Comment by thekingofcity** [comment]
好像是无法使用了, 有什么服务商推荐吗, 看来要换一个重写下打码模块了?

**Comment by OneCodeMonkey** [comment]
用这个 http://www.chaojiying.com/ 实测能通。

**Comment by thekingofcity** [comment]
> 
> 
> 用这个 http://www.chaojiying.com/ 实测能通。

有兴趣实现一下吗哈哈?

**Comment by OneCodeMonkey** [comment]
> > 用这个 http://www.chaojiying.com/ 实测能通。
> 
> 有兴趣实现一下吗哈哈?

后面我会把整体这块做个多平台兼容，发一版 release
临时要用的话，需要改下 utils/code_verification.py  和 login/login.py 就行了，我这边已经接上在用了。

**Comment by thekingofcity** [comment]
> 
> 
> > > 用这个 http://www.chaojiying.com/ 实测能通。
> > 
> > 
> > 有兴趣实现一下吗哈哈?
> 
> 后面我会把整体这块做个多平台兼容，发一版 release
> 临时要用的话，需要改下 utils/code_verification.py 和 login/login.py 就行了，我这边已经接上在用了。

不知实现是否有patch分支可以参考 :)

**Comment by OneCodeMonkey** [comment]
@thekingofcity 我开了一个分支 temp_verification，替换掉里面的账户信息就可以用了

**Comment by OneCodeMonkey** [comment]
有需要的可以先切这个分支用着

**Comment by thekingofcity** [comment]
好的, 我也merge下试试这家

**Comment by thekingofcity** [comment]
@OneCodeMonkey 😂云打码是不是又好了

**Comment by OneCodeMonkey** [comment]
是的。
