### ISSUE TITLE
能否用多线程代替多台机器来爬取？

### ISSUE THREAD

**Issue by myrainbowandsky** [SpiderClub/weibospider#191]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？

尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

用manager管理
用pipe line传递微博信息

或者

用多个docker模拟多台机器进行爬取？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by thekingofcity** [comment]
能, 详细见readme, 但请注意过快的请求会导致ip被封锁
