### ISSUE TITLE
如何限定时间段，爬取从某年月日到某年月日的微博？

### ISSUE THREAD

**Issue by myrainbowandsky** [SpiderClub/weibospider#198]

**Comment by OneCodeMonkey** [comment]
@myrainbowandsky已知的有两种：
1.搜索页可以加起止时间：s.weibo.com/weibo?q={关键词}&typeall=1&suball=1&timescope=custom:2020-03-01-1:2020-03-02-2

2.用户页参考这个：weibo.com/{uid}?is_all=1&stat_date=201909

**Comment by myrainbowandsky** [comment]
> @myrainbowandsky已知的有两种：
> 1.搜索页可以加起止时间：s.weibo.com/weibo?q={关键词}&typeall=1&suball=1&timescope=custom:2020-03-01-1:2020-03-02-2
> 
> 2.用户页参考这个：weibo.com/{uid}?is_all=1&stat_date=201909

感谢 作者回答 我去试试哦

**Comment by OneCodeMonkey** [comment]
没啥其他问题了吧？这个议题我关闭了
