### ISSUE TITLE
mysql数据库里user_relation这样表 一直是空，是哪里有问题？

### ISSUE THREAD

**Issue by myrainbowandsky** [SpiderClub/weibospider#199]
Ubuntu 18.04 python 3.6
master拉取。

weibo_data, wbuser,weibo_repost 也一直有大量数据产生。
唯独user_relation 这张表一直是空的，最有可能的原因是什么呢？：）

![截屏2020-03-2010 05 35](https://user-images.githubusercontent.com/35071732/77128156-6f1a8580-6a92-11ea-8fa0-90e0a6f200e5.png)

user_relation 对应哪个命令？
![截屏2020-03-2014 23 49](https://user-images.githubusercontent.com/35071732/77138738-8cf9e180-6ab6-11ea-8ca9-6fc994bba8e0.png)

**Comment by thekingofcity** [comment]
自行检查是否任务启动及流程

**Comment by myrainbowandsky** [comment]
怎么启动，

> 自行检查是否任务启动及流程

具体哪个命令启动

**Comment by thekingofcity** [comment]
```fans_followers```这个队列

**Comment by OneCodeMonkey** [comment]
没有抓过粉丝列表和关注列表。这个表就是空的

**Comment by myrainbowandsky** [comment]
> 没有抓过粉丝列表和关注列表。这个表就是空的

![截屏2020-03-2116 49 15](https://user-images.githubusercontent.com/35071732/77222201-74f88f80-6b94-11ea-8ff4-64ab508b8e56.png)

报错

**Comment by myrainbowandsky** [comment]
> `fans_followers`这个队列

报错


```
[2020-03-21 16:54:57,151: INFO/MainProcess] Received task: tasks.user.crawl_follower_fans[2768cfb2-337d-4cbf-8aea-635c971d45de]  
[2020-03-21 16:54:57,153: ERROR/ForkPoolWorker-1] Task tasks.user.crawl_follower_fans[6c223b6f-8f48-46b3-b59d-c308763835fb] raised unexpected: AttributeError("'NoneType' object has no attribute 'other_crawled'",)
Traceback (most recent call last):
  File "/home/wentao/programming/weibospider/WeiboSpider/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/wentao/programming/weibospider/WeiboSpider/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/wentao/programming/weibospider/tasks/user.py", line 12, in crawl_follower_fans
    if seed.other_crawled == 0:
AttributeError: 'NoneType' object has no attribute 'other_crawled'
```

**Comment by thekingofcity** [comment]
检查表[```seed_ids```](https://github.com/SpiderClub/weibospider/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E#seed_ids)

**Comment by myrainbowandsky** [comment]
> 检查表[`seed_ids`](https://github.com/SpiderClub/weibospider/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8%E5%AD%97%E6%AE%B5%E8%AF%B4%E6%98%8E#seed_ids)

seed_ids 也里有东西，：

![截屏2020-03-2212 38 04](https://user-images.githubusercontent.com/35071732/77241733-feae6880-6c39-11ea-8128-a89ca86d06bf.png)




但是以下三个表一直空
![截屏2020-03-2212 39 46](https://user-images.githubusercontent.com/35071732/77241769-65338680-6c3a-11ea-8f01-7981e29c7ca0.png)

**Comment by thekingofcity** [comment]
检查```crawl_follower_fans```函数入参以及```seed_ids```是否有此条uid记录

**Comment by myrainbowandsky** [comment]
> 检查`crawl_follower_fans`函数入参以及`seed_ids`是否有此条uid记录


在user.py打印uid 是可以的：
![截屏2020-03-2314 25 34](https://user-images.githubusercontent.com/35071732/77284512-338dee80-6d12-11ea-9043-6db6db19b95b.png)

但是提示seed没有other_crawled属性

![截屏2020-03-2314 23 32](https://user-images.githubusercontent.com/35071732/77284760-c75fba80-6d12-11ea-8220-26b356ab6f83.png)



在dao.py找不到other_crawled属性
![截屏2020-03-2314 31 30](https://user-images.githubusercontent.com/35071732/77284949-3e954e80-6d13-11ea-9350-5fe36fac602c.png)

**Comment by thekingofcity** [comment]
那大概便是```seed_ids``无此条uid记录

**Comment by myrainbowandsky** [comment]
> 那大概便是```seed_ids``无此条uid记录



crawl_follower_fans 是从seed_ids 读取数据吗？

seed_ids现在有大批数据，怎么让 crawl_follower_fans 读呢
![Screenshot from 2020-03-23 20-25-45](https://user-images.githubusercontent.com/35071732/77312315-1c1c2900-6d45-11ea-89d8-39d2d1f512ed.png)

**Comment by thekingofcity** [comment]
可以尝试重写11行SeedidsOper.get_seed_by_id(uid)
使用类似这样的函数SeedidsOper.get_seed_ids从数据库中获取数据

**Comment by myrainbowandsky** [comment]
> 可以尝试重写11行SeedidsOper.get_seed_by_id(uid)
> 使用类似这样的函数SeedidsOper.get_seed_ids从数据库中获取数据

我先去试一试看看。

**Comment by myrainbowandsky** [comment]
> 可以尝试重写11行SeedidsOper.get_seed_by_id(uid)
> 使用类似这样的函数SeedidsOper.get_seed_ids从数据库中获取数据


报错，是一个bug吗？
```
[2020-03-25 19:07:12,388: ERROR/ForkPoolWorker-1] Task tasks.user.crawl_follower_fans[23f3c1fd-fc6e-4c5b-b0cc-5d5c6a9ad068] raised unexpected: TypeError('expected string or bytes-like object',)
Traceback (most recent call last):
  File "/home/wentao/programming/weibospider/WeiboSpider/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/wentao/programming/weibospider/WeiboSpider/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/wentao/programming/weibospider/tasks/user.py", line 19, in crawl_follower_fans
    rs = get_fans_or_followers_ids(uid, 1, 1)
  File "/home/wentao/programming/weibospider/page_get/user.py", line 159, in get_fans_or_followers_ids
    urls_length = public.get_max_crawl_pages(page)
  File "/home/wentao/programming/weibospider/page_parse/user/public.py", line 223, in get_max_crawl_pages
    m = re.search(pattern, script.string)
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```



user.py 中 script.string 有bug
script.string 这里有bug无法判断是哪个类型一会nontype，一会是<class 'bs4.element.NavigableString'>
无论哪种类型都无法用re 模块抓取


```
 for script in scripts:
        #print('i am in '+dir_path,'script is '+script)
        #print('script.string:',script.string)
        
        print('type pattern',pattern)
        print('pattern', pattern)
        print('type:',type(script.string))
        
        m = re.search(pattern, script.string)


        if m and 'pl.content.followTab.index' in script.string:
            all_info = m.group(1)
            cont = json.loads(all_info).get('html', '')
            soup = BeautifulSoup(cont, 'html.parser')
            pattern = 'uid=(.*?)&'

            if 'pageList' in cont:
                urls2 = soup.find(attrs={'node-type': 'pageList'}).find_all(attrs={
                    'class': 'page S_txt1', 'bpfilter': 'page'})
                length += len(urls2)
    return length
```
![截屏2020-03-2521 14 25](https://user-images.githubusercontent.com/35071732/77535265-b1eabc00-6edd-11ea-8659-d8cee8ef510b.png)

**Comment by thekingofcity** [comment]
与issue无关, 建议新开issue
