### ISSUE TITLE
微博关键词搜索 create_time 一栏有四种时间格式，能否统一为一个 20**年**月**日的形式？

### ISSUE THREAD

**Issue by myrainbowandsky** [SpiderClub/weibospider#200]
’2020-02-06 22:21'
‘2019年02月04日 10:48'
'今天06:09'
'21秒前'
怎么统一一个输出格式

**Comment by OneCodeMonkey** [comment]
这个时间戳的噪音可以临时自己写个函数格式化输出，包含中文噪音的时间戳的几种情形可以枚举出来。每种单独做下处理转换就行。

**Comment by thekingofcity** [comment]
这个格式化可以见[解析评论的时间戳](https://github.com/SpiderClub/weibospider/blob/master/page_parse/comment.py#L121), 不过需自行实现搜索的格式化了

**Comment by myrainbowandsky** [comment]
> 这个格式化可以见[解析评论的时间戳](https://github.com/SpiderClub/weibospider/blob/master/page_parse/comment.py#L121), 不过需自行实现搜索的格式化了
嗯嗯，我实现了一下，感觉还有点小瑕疵@
