### ISSUE TITLE
请问这个爬虫爬取关键词的话是只能爬取50页的上限吗？

### ISSUE THREAD

**Issue by SinruW** [SpiderClub/weibospider#214]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？

尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by OneCodeMonkey** [comment]
对，微博那边限制的页数只有五十页。
要想爬多一点，可以在 query 条件里加一个时间条件，细分到每一个小时区间。这样每个小时里还能再爬 50 页。
