### ISSUE TITLE
通过关键字搜索爬取内容比预期少

### ISSUE THREAD

**Issue by conghuaicai** [SpiderClub/weibospider#53]
1. 我在kewords关键字表中填入如下信息：
id   keyword  enable
1    深圳 冰雹   1
2    深圳 暴雨    1
....
并且在login_info表中填好账号，按照文档启动进行了如下操作:
- celery -A tasks.workers worker -l info -c 1
- python login_first.py
- celery beat -A tasks.workers -l info
最后程序可以正常爬取数据，但是我发现通过搜索爬取的内容比预期的少，比如我手动通过**深圳 冰雹**，去搜索，看了代码好像是默认是原创的搜索方式，我就在高级搜索里面选择原创进行搜索，得到的页面至少有50页，但是，我日志的输出如下

2017-10-25 07:00:32 - crawler - INFO - the crawling url is http://s.weibo.com/weibo/%E6%B7%B1%E5%9C%B3%20%E5%86%B0%E9%9B%B9&scope=ori&suball=1&page=1
2017-10-25 07:00:50 - crawler - INFO - keyword 深圳 冰雹 has been crawled in this turn

操作之前我已经帮redis的内容都清空，我看了下代码，在tasks/search下判断该轮爬取是否结束有两处，一是通过微博mid看该微博是否在数据库存在，二是查看是否还有下一页，对于第一条，我觉得不是很合理，因为在多个关键字搜索的结果中是可能存在重复的微博内容的，不知道这样想是不是对的，我自己把return改成continue，但是还是发现爬取的页面数比较少就直接说该轮结束。

操作系统 Ubuntu 16.04
WeiboSpider 1.7.2

**Comment by ResolveWang** [comment]
你提出的第一个观点很正确，我以前确实是没考虑到多个关键词搜索结果重复的现象。可不可以考虑要不要加一个`mid+keyword`组成的一个column，来规避这种错误。

第二类情况，你在改过代码后，是否有清空数据库，不然它判断到有重复的就不会抓取了。这个问题我最近也发现了，我发现最近它的返回页数似乎是很不稳定。对于多页的结果，有时候解析的时候只会返回少数几页，但是它这个现象很随机。这个问题我也还在考虑怎么解决。

你有好的点子了没？这两个问题你都可以尝试改改，然后提个PR一起完善。

**Comment by ResolveWang** [comment]
目前我们可能得着重解决数据完整性这个问题了。因为不止是搜索，如果在不登录的情况下，有时候转发和评论的完整性也有问题，不过不登录的版本在master分支，由于还不稳定，所以一直没发布。

这个问题你要有精力也可以看看:smile:期待你的贡献

**Comment by neuclil** [comment]
对于判断我该轮爬取是否结束，我的想法如下：
1. 先通过微博mid判断该微博是否已经在数据库中存在，如果存在就跳过。
2. 对于多页的结果，我自己手动在微博上搜的时候，如果一个搜索结果只有10页， 我强行将url后面page改为11，会得到如下字段，是否可以考虑用如下字段来判断是否对多页的结果已经爬取结束。
```
抱歉，未找到“深圳 冰雹”相关结果。

建议:
您可以尝试更换关键词，再次搜索。
您可以关注萌小搜@微博搜索获取搜索技巧。
您也可以尝试在全网内搜索：深圳 冰雹
```

**Comment by ResolveWang** [comment]
对于第一点，我不是很赞同，因为这样做的话，就不能保证增量抓取了，本来搜索限制就很严格了，这样无疑会加大被封的可能性。还有一种解决方案，可以在存数据的时候，在redis或其它缓存中为每个搜索词加个最新更新时间，这样在进行高级搜索的时候便可以从那个时间开始搜索，再结合你提的这个我觉得就会很合理了。

对于第二点，我很赞同。如果在不满配置文件最大翻页限制或者微博系统最大翻页限制的时候，不妨用这种策略。

**Comment by neuclil** [comment]
嗯，第一点，通过存储每次爬取的时间来进行增量抓取确实比较合理，我找个时间实现一下。：）

**Comment by neuclil** [comment]
之前说到的通过时间来进行增量爬取，在后面的实践中，发现不需要这样做，因为在 `keywords_wbdata`这个表中， keyword_id + wb_id 是唯一的，这说明，我们在进行增量爬取的时候，只需要判断当前这条微博，在这个关键字搜索下是否已经爬取过，即只需要在数据库中判断 cur_keyword_id + cur_weibo_id 是否在 `keywords_wbdata`中存在即可。  本周，我再测试一下，不知道我这样想，有没有问题？

**Comment by ResolveWang** [comment]
`keyword+wbid`这种方式做增量是很合理的，如果结果是按时间排序的话。这样也不用担心不同关键词搜出来相同结果导致误判

**Comment by conghuaicai** [comment]
经测试，由于搜索结果是按照时间排序，keyword+wbid能够解决增量爬取和多关键搜索的问题，代码已经提交到dev分支。
