### ISSUE TITLE
dockerize?

### ISSUE THREAD

**Issue by oeddyo** [SpiderClub/weibospider#55]
看了眼配置环境，可能配起来就吓跑一堆用户了，有没有可能出个docker的image?

**Comment by ResolveWang** [comment]
你说的是`docker compose`吗，还是整体的把代码和数据库等都打包成一个image呢？

**Comment by oeddyo** [comment]
一个Dockerfile应该就好了，把需要的配置都写进去(i.e. mysql配置，redis配置etc），这样降低试用门槛的话相信用户会更多的 :)

**Comment by ResolveWang** [comment]
你是说的[这个](https://github.com/SpiderClub/weibospider/wiki/%E4%BD%BF%E7%94%A8Docker%E6%9E%84%E5%BB%BA%E5%92%8C%E9%83%A8%E7%BD%B2%E9%A1%B9%E7%9B%AE)吗

**Comment by oeddyo** [comment]
对，一开始readme里没看到：）

感谢
