### ISSUE TITLE
希望新增爬取“查看对话”功能

### ISSUE THREAD

**Issue by yezuoxian** [SpiderClub/weibospider#57]
在微博评论页下有个查看对话的按钮，可以查看评论中的对话。是十分有用的对话数据来源。

**Comment by yezuoxian** [comment]
如果可以希望作者可以新增这个功能，十分感谢

**Comment by ResolveWang** [comment]
可能最近功能上不会增加很大的功能，我会考虑的。你有能力也可以尝试自己实现一下，可以给该项目贡献代码。
这个功能等我春节期间去调研一下吧，目前精力不允许。

**Comment by yezuoxian** [comment]
#63
