### ISSUE TITLE
celery的send_task方法推荐任务嵌套调用吗？

### ISSUE THREAD

**Issue by dingweihua** [SpiderClub/weibospider#60]
比如说user_first.py中，程序中使用了任务调用任务的方式：
execute_user_task 调用任务 crawl_person_infos，crawl_person_infos再在内部调用任务crawl_follower_fans。问题是：
1. celery官方推荐使用任务嵌套调用任务的模式吗？（比如说官方有chain的操作）
2. 如果使用任务嵌套调用的方式，并发较高时会不会容易造成队列阻塞的情况？
谢谢！

**Comment by ResolveWang** [comment]
用任务链更好，下一次的release会重构部分代码，将嵌套任务改用链式调用。
为什么任务嵌套会在高并发的时候造成队列阻塞？难道你用链式调用就不会了吗？链式调用不也是把一个个子任务分配到各个机器上吗？队列阻塞很多情况下是由于资源不足或者你的任务大小分割不合理,我认为和嵌套任务与否关系不是很大

**Comment by dingweihua** [comment]
@ResolveWang 
嗯 你说的有道理。
因为项目里所有的嵌套调用任务都是不需要等待返回结果的，所以不会阻塞。而且官方也不推荐使用嵌套调用需要等待返回值的任务。

**Comment by ResolveWang** [comment]
是的，项目设计的时候，都没在各个task function中传递参数，因为某些object要在celery中做序列化再传递会比较麻烦，这个倒是可以改进的地方。不过目前还没改动得那么细致，有些功能性的东西还没做完，现在精力也十分有限。
