### ISSUE TITLE
总显示被ban

### ISSUE THREAD

**Issue by weifeng91** [SpiderClub/weibospider#62]
![image](https://user-images.githubusercontent.com/11347898/34508442-5dd42db0-f07a-11e7-8706-7f8490abf72c.png)
总显示被ban，数据库里面添加了seedsid，也就只有一条记录，不会全部爬取

**Comment by ResolveWang** [comment]
总显示被ban，你手动登陆试试看看你的账号是否正常呢？
不会全部爬取是因为你没理清楚该项目的工作流程，项目是使用定时任务做增量爬取的，比如这一轮你的seedid插入了一个，那么这一轮只会抓取一个账号，需要等下一次定时任务启动才会抓上一轮新获取的seed ids.
