### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by panhsh** [SpiderClub/weibospider#66]
win7系统
按照readme配置方法一直走，到运行login-first这步时，无法登陆

=====================================================
pycharm的显示
F:\Anaconda\python.exe E:/pyCharm_files/weibospider-master/first_task_execution/login_first.py
F:\Anaconda\lib\site-packages\pymysql\cursors.py:166: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 481")
  result = self._query(query)
F:\Anaconda\lib\site-packages\pymysql\cursors.py:166: Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  result = self._query(query)
2018-01-19 12:25:52 - crawler - INFO - The login task is starting...

Process finished with exit code 0
====================================================
celery的显示

E:\pyCharm_files\weibospider-master>celery -A tasks.workers -Q login_queue,user_
crawler,fans_followers,search_crawler,home_crawler worker -l info -c 1

 -------------- celery@admin-PC v4.1.0 (latentcall)
---- **** -----
--- * ***  * -- Windows-7-6.1.7601-SP1 2018-01-19 12:32:58
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         weibo_task:0x4e2da58
- ** ---------- .> transport:   redis://127.0.0.1:6379/5
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> fans_followers   exchange=fans_followers(direct) key=for_fans
_followers
                .> home_crawler     exchange=home_crawler(direct) key=home_info
                .> login_queue      exchange=login_queue(direct) key=for_login
                .> search_crawler   exchange=search_crawler(direct) key=for_sear
ch_info
                .> user_crawler     exchange=user_crawler(direct) key=for_user_i
nfo

[tasks]
  . tasks.comment.crawl_comment_by_page
  . tasks.comment.crawl_comment_page
  . tasks.comment.execute_comment_task
  . tasks.dialogue.crawl_dialogue
  . tasks.dialogue.crawl_dialogue_by_comment_id
  . tasks.dialogue.crawl_dialogue_by_comment_page
  . tasks.dialogue.execute_dialogue_task
  . tasks.downloader.download_img_task
  . tasks.home.crawl_ajax_page
  . tasks.home.crawl_weibo_datas
  . tasks.home.execute_home_task
  . tasks.login.execute_login_task
  . tasks.login.login_task
  . tasks.repost.crawl_repost_by_page
  . tasks.repost.crawl_repost_page
  . tasks.repost.execute_repost_task
  . tasks.search.execute_search_task
  . tasks.search.search_keyword
  . tasks.user.crawl_follower_fans
  . tasks.user.crawl_person_infos
  . tasks.user.execute_user_task

[2018-01-19 12:32:59,092: INFO/MainProcess] Connected to redis://127.0.0.1:6379/
5
[2018-01-19 12:32:59,104: INFO/MainProcess] mingle: searching for neighbors
[2018-01-19 12:32:59,678: INFO/SpawnPoolWorker-1] child process 5300 calling sel
f.run()
[2018-01-19 12:33:00,128: INFO/MainProcess] mingle: all alone
[2018-01-19 12:33:00,171: INFO/MainProcess] celery@admin-PC ready.
[2018-01-19 12:34:33,965: INFO/MainProcess] Received task: tasks.login.login_tas
k[fc29ccb5-defd-4dbd-8fbd-a71cb250a1ba]
[2018-01-19 12:34:34,165: ERROR/MainProcess] Task handler raised error: ValueErr
or('not enough values to unpack (expected 3, got 0)',)
Traceback (most recent call last):
  File "f:\anaconda\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "f:\anaconda\lib\site-packages\celery\app\trace.py", line 525, in _fast_t
race_task
    tasks, accept, hostname = _loc
ValueError: not enough values to unpack (expected 3, got 0)
[2018-01-19 12:34:43,968: INFO/MainProcess] Received task: tasks.login.login_tas
k[44a666b6-7811-4b70-aabb-6a5f46069035]
[2018-01-19 12:34:43,973: ERROR/MainProcess] Task handler raised error: ValueErr
or('not enough values to unpack (expected 3, got 0)',)
Traceback (most recent call last):
  File "f:\anaconda\lib\site-packages\billiard\pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "f:\anaconda\lib\site-packages\celery\app\trace.py", line 525, in _fast_t
race_task
    tasks, accept, hostname = _loc
ValueError: not enough values to unpack (expected 3, got 0)
=====================================================
不好意思，刚接触这个，不是很懂

**Comment by ResolveWang** [comment]
感谢反馈。根据这个
`F:\Anaconda\lib\site-packages\pymysql\cursors.py:166: Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")`信息，初步判断可能是数据库版本的问题，建议用`mysql5.7`,你可以打印一下[tasks/login.py](https://github.com/SpiderClub/weibospider/blob/master/tasks/login.py)中获取的账号，看看是否真的获取到了
```python3
@app.task(ignore_result=True)
def execute_login_task():
    infos = LoginInfoOper.get_login_info()
    # Clear all stacked login tasks before each time for login
    Cookies.check_login_task()
    crawler.info('The login task is starting...')
    # 这里看一下
    print('账号数量为{}'.format(len(infos)))
    for info in infos:
        # 这里看一下
        print(info.name, info.password)
        app.send_task('tasks.login.login_task', args=(info.name, info.password), queue='login_queue',
                      routing_key='for_login')
        time.sleep(10)
```

另外，给两个建议:
1.从[release](https://github.com/SpiderClub/weibospider/releases)下载代码
2.用linux操作系统（可以用虚拟机或者docker），windows在最近的几个版本中都没测试过了.

有问题再读读[wiki](https://github.com/SpiderClub/weibospider/wiki)，无法解决再反馈吧
