### ISSUE TITLE
1.无法爬取转发微博和评论微博；2.主页微博抓取不全

### ISSUE THREAD

**Issue by Kaixinguoer210** [SpiderClub/weibospider#68]
1. 环境 win10，celery版本3.1.25，最新版本的weibospider，通过
`git clone https://github.com/SpiderClub/weibospider.git`获得
2. 操作：严格按照快速开始中前9项进行，在一切正常后。
`python first_task_execution/login_first.py      # 发送登陆任务`，
`python first_task_execution/user_first.py  # 抓取用户个人信息`
`python first_task_execution/home_first.py  # 抓取用户主页微博`
`python first_task_execution/repost_first.py  # 抓取转发微博`
3. 获得结果：celery端未出现任务接收提示，也未进行转发微博爬取，再次尝试爬取评论，同样不能成功。（可以确信登陆、用户信息爬取以及用户主页微博爬取均已完成）

**Comment by ResolveWang** [comment]
感谢反馈。1. 项目版本建议使用1.7.2， 2.评论和转发如果没反应，请确定一下是否指定了-Q参数，指定评论等的任务队列 3.建议用Linux系统哈      手机打字，这几个问题确认了有疑问再提哈

**Comment by violetmmhh** [comment]
我爬一个人的微博有8000多条，可是我爬了45天就不动了，试了好多次都是这样，这是怎么回事啊

**Comment by ResolveWang** [comment]
@violetmmhh 你所爬的用户的原创微博是否有8000多条？这个项目原本抓取的是原创微博，不是你看到的默认的那个页面，如果你想抓所有微博，可能你需要自己改一些代码
