### ISSUE TITLE
Why only crawls origin weibo?

### ISSUE THREAD

**Issue by thekingofcity** [SpiderClub/weibospider#72]
tasks/home.py
\# only crawls origin weibo
HOME_URL = 'http://weibo.com/u/{}?is_ori=1&is_tag=0&profile_ftype=1&page={}'

what will happen when I replace the url with not origin?

**Comment by ResolveWang** [comment]
Because i don't need redundant weibo content because the search result of origin weibo sorted by time.If you replace the url for default search result, you must make a dupefilter and may change the code of parsing search pages.
