### ISSUE TITLE
演示视频链接失效了，大佬能否更新下呢，我是新手，想看下演示视频

### ISSUE THREAD

**Issue by Overdo** [SpiderClub/weibospider#73]
演示视频链接失效了，大佬能否更新下呢，我是新手，想看下演示视频

**Comment by ResolveWang** [comment]
链接: https://pan.baidu.com/s/1mjhqywS  密码: butv。

视频未进行更新，可以查看[wiki](https://github.com/SpiderClub/weibospider/wiki)，里面有详细的文档
