### ISSUE TITLE
能不能再分享一下爬到的数据...

### ISSUE THREAD

**Issue by NullWang27** [SpiderClub/weibospider#78]
本来想要自己从头开始跑一遍的..发现进度太慢..能不能请博主再分享一下最近的数据 有关用户微博表 以及个人信息表的数据  做机器学习和NLP的原料..(ㄒoㄒ)

**Comment by ResolveWang** [comment]
数据自己爬吧，我以前爬的全删完了

**Comment by NullWang27** [comment]
好吧 以前很少用linux 太折磨了..  还是很感谢博主！

**Comment by NullWang27** [comment]
绝知此事要躬行  把这个issue关了 再次感谢博主！

**Comment by ResolveWang** [comment]
客气。使用过程中有问题先看文档和以前的issue，再有问题欢迎提出来
