### ISSUE TITLE
Possible way to fix '@@tx_isolation' is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by thekingofcity** [SpiderClub/weibospider#80]
Every time I run tasks, I will get the following

     '@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead

Seems like the old version 1.1.9 of SQLAlchemy assigned in requirement.txt to be the culprit.

[More information](https://stackoverflow.com/questions/47026599/mysql-giving-deprecated-warning)

**Comment by ResolveWang** [comment]
Sorry that i can't reproduce the warning even I know many users come across this problem.If you solve the problem by rolling back or updating the sqlalchemy(or pymysql), please pull a request and merge it into the master

**Comment by thekingofcity** [comment]
OK, I will test the 1.1.15 in the following days, and check whether that works.

**Comment by ResolveWang** [comment]
@thekingofcity It sounds great, best wishes
