### ISSUE TITLE
你好，非常感谢能开源这么好的微博爬取工具，我想问 这个tasks/workers.py 定时任务，里面的时间可以再调得频繁一点吗，如果调的频繁点会出现什么问题吗

### ISSUE THREAD

**Issue by lovenodejs** [SpiderClub/weibospider#81]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？

尽量把你的操作过程描述清楚，最好能够复现问题。

2.你期望的结果是什么？

3.实际上你得到的结果是什么？

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？是否有读本项目的[常见问题](https://github.com/SpiderClub/weibospider/wiki/%E9%A1%B9%E7%9B%AE%E4%BD%BF%E7%94%A8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)？

**Comment by ResolveWang** [comment]
可能出现的问题就是账号被封，其它没啥问题，你要账号多的话，可以频繁一些。而且抓取不同模块，微博的不同模块限制的抓取间隔也不一样，目前还没做细粒度的控制。

**Comment by ResolveWang** [comment]
搜索的话，限制很严格，如果一个账号的话，你试试20~30秒吧，用户主页的话，大概十来秒。这个我也不能说绝对是这样，只能给一个大概的范围

**Comment by lovenodejs** [comment]
那岂不是在源码文件中原来设置的小时已经是很宽松了的？也就是在tasks/workers.py  设置 hours  minutes seconds 成需要间隔多少时间对应的值是吗？

**Comment by ResolveWang** [comment]
读文档吧。我感觉你没读文档，我希望你是读了文档再来提问的。

一个是抓取间隔，一个是定时任务间隔，两个是不一样的

**Comment by lovenodejs** [comment]
好的，麻烦了
