### ISSUE TITLE
登录失败提示account need verification for login

### ISSUE THREAD

**Issue by qghc** [SpiderClub/weibospider#94]
在提交Issue之前请先回答下面问题，谢谢！

1.你是怎么操作的？
你好，小白遇到一个问题，大神帮我看一下哈，非常感谢。
按照readme操作到第10步。发起登录任务后，节点中进行了打码、登录，但是提示account need verification for login，是需要手机验证还是什么？我用浏览器登录就不需要验证别的，填了验证码就登录成功了。

2.你期望的结果是什么？
希望能登录上。

3.实际上你得到的结果是什么？
登录，但是提示account need verification for login

4.你使用的是哪个版本的WeiboSpider? 你的操作系统是什么？
v1.7.2，系统Ubuntu 16.04
![](https://upload-images.jianshu.io/upload_images/3473742-a8a8f3deffee03c3.png)

**Comment by ResolveWang** [comment]
这个提示应该是没有任何问题的，这是正常提示的内容，只是作为提示内容显示

你执行其他任务看看有不有问题，或者在redis中看看是否有cookies

**Comment by qghc** [comment]
今天试了下，结果控制台只打出“云打码余额”，连验证码也没有打出来，也没走到“account need verification for login”这一步，redis中也没有cookies。
![Alt text](https://upload-images.jianshu.io/upload_images/3473742-9a84988269a53162.png)

**Comment by qghc** [comment]
今天试了一下，执行其他任务时提示没有cookies，而且redis中确实没有cookies

**Comment by ResolveWang** [comment]
看看`logs`文件夹中有不有什么错误呢？单从这里看，好像没看到有啥错误

然后你自己也可以通过[login.py](https://github.com/SpiderClub/weibospider/blob/master/login/login.py)进行调试，主要看看`get_session()`这个函数
```
other.info('Login successful! The login account is {}'.format(name))
Cookies.store_cookies(name, session.cookies.get_dict())
# 打印cookies看看是否有内容，如果中途有什么问题，可能并不会运行到这里
print(name, session.cookies.get_dict())
return session
```

有问题再反馈哈
